### ISSUE TITLE
Forms Page - Not Sure Why the Word AND is Capitalized

### ISSUE THREAD

**Issue by jfc3-dol** [Section508Coordinators/ICTTestingBaseline#10]
On the Form page ( https://section508coordinators.github.io/ICTTestingBaseline/10Forms.html ), I'm not sure why the word AND is capitalized between the G115 and H49 links? 

Maybe make the text bold instead of capitalized, so people realize there are two links on the line, or maybe if possible, place the second link in a separate list item.

The same applies to the text below.

`<title>` element, AND the `<title>`

**Comment by kengdoj** [comment]
Cloned issue to atbcb repo
