### ISSUE TITLE
Consider combining Frames with Page Titles

### ISSUE THREAD

**Issue by drewnielson** [Section508Coordinators/ICTTestingBaseline#114]

**Comment by mraccess77** [comment]
@drewnielson Could you provide more details on why you recommend combining page title and frames?

**Comment by drewnielson** [comment]
@mraccess77, it might be worth a call to Al to get more of the reasoning for the suggestion. I believe his thought is that even though we are talking about different elements, he see's them as conceptually the same.

**Comment by drewnielson** [comment]
Determined to keep page titles separate from frames/iframes.
