### ISSUE TITLE
Additional WAF Limitations

### ISSUE THREAD

**Issue by mraccess77** [Section508Coordinators/ICTTestingBaseline#116]
Following could be added to the list of additional WAF limitations
* Fieldset and legend Favlet does not pick up ARIA role group and radiogroup
* Frames Favlet does not support ARIA based accessible names for iframes like aria-label
* JavaScript link favlet does not seem to catch non links that use JavaScript such as onclick on a div
* Links favlet does included ARIA in accessible name nor alt text from images in links
* Show Data tables favlet does include ARIA roles for tables are accessible name on tables
* Show Images favlet does not include ARIA accessible names, SVG, or role of img

**Comment by drewnielson** [comment]
Have neglected comment on this issue for obviously far too long. I believe all issues are now addressed in the ANDI tool. No longer tracking WAF limitations in this repository.
