### ISSUE TITLE
fix link in 02FocusVisible

### ISSUE THREAD

**Issue by drewnielson** [Section508Coordinators/ICTTestingBaseline#205]
Test 2
https://section508coordinators.github.io/ICTTestingBaseline/02FocusVisible.html

has the content
…
Advisory: Tips for streamlined test processes
•	The clarity of visible focus is subjective and the minimum level is the browser’s (or OS platform) default display setting for indicating focus. Browsers may also represent visual focus differently in specific situations.
•	This test may be performed simultaneously with Baseline 1: Keyboard Access.
…
The link to baseline 1 is incorrect  It gets a 404 error.
Current Link is: https://github.com/Section508Coordinators/ICTTestingBaseline/blob/master/docs/01Keyboard
And it should be: https://section508coordinators.github.io/ICTTestingBaseline/01Keyboard.html

**Comment by kengdoj** [comment]
yes, concur on this change. Do you want to do a pull request?

**Comment by drewnielson** [comment]
Yep, I’ll make the change and put in a pull request. Just wanted to make
sure you hadn’t already caught it first with one of your other edits.

**Comment by kengdoj** [comment]
No, I don't see a pull request for Test 02 from me... thanks for catching it!

**Comment by kengdoj** [comment]
fixed previously. not sure of PR #, but link was fixed.
