### ISSUE TITLE
Baseline 18: CSS before and after content

### ISSUE THREAD

**Issue by kengdoj** [Section508Coordinators/ICTTestingBaseline#209]
> Test Procedure for SC 1.3.1 Info Relationships
Identify Content
Meaningful page content inserted by CSS using ::before or ::after
Test Instructions
For meaningful content provided via CSS, check that equivalent information is available without the CSS content.
Test Results
If any of the above checks fail, then SC 1.3.1 and Baseline Requirement 18 fail.

Is this test still needed with [accessible name computation](https://www.w3.org/TR/accname-1.1/#mapping_additional_nd_te) updated to include pseudo content?

> 2F. Check for CSS generated textual content associated with the current node and include it in the accumulated text. The CSS :before and :after pseudo elements [CSS2] can provide textual content for elements that have a content model.
> - i. For :before pseudo elements, User agents MUST prepend CSS textual content, without a space, to the textual content of the current node.
> - ii. For :after pseudo elements, User agents MUST append CSS textual content, without a space, to the textual content of the current node.

**Comment by kengdoj** [comment]
Raise this with @bruce-usab: 

Is [F87](https://www.w3.org/TR/WCAG20-TECHS/F87.html) still a valid failure with the text alternative computation updated to include pseudo elements?

**Comment by kengdoj** [comment]
This test page (created for a different purpose) with font icons may be helfpufl: 

https://kengdoj.github.io/new-bookmarklets/test_pages/insertedtextandicons.html

**Comment by kengdoj** [comment]
There are [F87-related issues](https://github.com/w3c/wcag/issues?q=is%3Aissue+f87) on W3C/WCAG.

In [w3c/wcag Issue #1007](https://github.com/w3c/wcag/issues/1007), April 2020, it was raised that AT support for pseudo-content has improved so F87 should be modified. 

Reading through the issues, screen reader support for pseudo content seems to not be the focus anymore since screen reader support has improved. Looks like F87 remains because assistive technology that overrides CSS (do screen magnifiers do this?) or a user's personal style sheet may cause meaningful CSS content to be missed.

There was an update to F87 between 2.0 and 2.1:

From [2.0's F87](https://www.w3.org/TR/WCAG20-TECHS/F87.html) test procedure: 

> If the inserted content is not decorative, check that the information is _**provided to assistive technologies and is also available when CSS is turned off**_.

To [2.1's F87](https://www.w3.org/WAI/WCAG21/Techniques/failures/F87.html) test procedure: 

> Check that non-decorative information presented by the generated content is **_available when styles are overridden_**.

**Comment by bruce-usab** [comment]
Thanks @kengdoj for finding that open issue with W3C/WCAG!

**Comment by kengdoj** [comment]
"Overridden" means using another style sheet:

How to use a custom style sheet:

- [Firefox](https://davidwalsh.name/firefox-user-stylesheet)

- Chrome and Edge need an add on/extension

- [Safari](http://theoveranalyzed.net/2018/3/16/safaris-custom-style-sheet)

- [Internet Explorer](https://mcmw.abilitynet.org.uk/using-your-own-style-sheet-internet-explorer-windows-10)

**Comment by kengdoj** [comment]
Working group decision: remove this test from Baseline

**Comment by kengdoj** [comment]
Updates made in PR #227
