### ISSUE TITLE
Modify 3. Focus Order for revealed content

### ISSUE THREAD

**Issue by kengdoj** [Section508Coordinators/ICTTestingBaseline#210]
Modify test step 3 and move it so that it is done sooner in the test instructions. 

Maybe replace current 1.i.a with "Check that the revealed content receive focus in an order that preserves meaning and operability."?

> Test Procedure for SC 2.4.3 Focus Order
> Test Instructions
> 1. Use the keyboard to navigate through interface components.
>    1. Use the keyboard to activate trigger controls that reveal hidden content (menus, dialogs, expandable tree list, etc.).
>       1. Check that focus is moved to the revealed content. (It is acceptable to TAB once or use an arrow key to move the focus forward into the revealed content.)
>       4. Advance the focus through the revealed content.
> 1. Use the keyboard to close/hide the revealed content.
>       1. Check that focus is returned to the trigger control. (It is acceptable to [Shift+ TAB] once or use an arrow key to move the focus backward to the trigger control.
> 7. Check that the focus order preserves the meaning and usability of the page.

**Comment by cliffbert** [comment]
Hmmm … how’s this:


Test Procedure for SC 2.4.3 Focus Order
Test Instructions

  1.  Use the keyboard to navigate through interface components.
     *   Use the keyboard to activate trigger controls that reveal hidden content (menus, dialogs, expandable tree list, etc.).
        *   Check that focus is moved to the revealed content in a sequence which preserves the meaning and usability of the page. (It is acceptable to TAB once or use an arrow key to move the focus forward into the revealed content.)
        *   Advance the focus through the revealed content.
  2.  Use the keyboard to close/hide the revealed content.
     *   Check that focus is returned to the trigger control. (It is acceptable to [Shift+ TAB] once or use an arrow key to move the focus backward to the trigger control.

**Comment by kengdoj** [comment]
I was thinking

> *   Check that focus is moved to the revealed content in a sequence which preserves the meaning and usability of the page. 

without the parenthesis part.

I don't think the number of tabs to the revealed content matters, whether it's next in the focus order or 5 tabs away, as long as meaning is preserved.

**Comment by cliffbert** [comment]
I’m down wid dat.

Cliff Soon
Senior Accessibility Analyst
OAST/DHS
________________________________

**Comment by kengdoj** [comment]
Or, how about this?

Check that the focus order to the revealed focusable content is in a sequence which preserves the meaning and usability of the page.

**Comment by cliffbert** [comment]
Totally1
