### ISSUE TITLE
6. Images - add consideration for role="none"

### ISSUE THREAD

**Issue by drewnielson** [Section508Coordinators/ICTTestingBaseline#211]

**Comment by kengdoj** [comment]
Should this be done with all/any other tests? 

From https://www.w3.org/TR/wai-aria-1.1/#none:

> none (role)§
> An element whose implicit native role semantics will not be mapped to the accessibility API. See synonym presentation.
> 
> NOTE
> Note regarding the ARIA 1.1 none role.§
> In ARIA 1.1, the working group introduced none as a synonym to the presentation role, due to author confusion surrounding the intended meaning of the word "presentation" or "presentational." Many individuals erroneously consider role="presentation" to be synonymous with aria-hidden="true", and we believe role="none" conveys the actual meaning more unambiguously.
> 
> Until implementations include sufficient support for role="none", web authors are advised to use the presentation role alone role="presentation" or redundantly as a fallback to the none role role="none presentation".

**Comment by drewnielson** [comment]
*Might* by sufficient to search for wherever we mention role="presentation", but might need to review more broadly as well.
