### ISSUE TITLE
6. Images - differentiate steps: calculate text alternative; determine whether equivalent

### ISSUE THREAD

**Issue by drewnielson** [Section508Coordinators/ICTTestingBaseline#213]
Consider dividing step into two separate steps. Also raises question of similar approach in other tests to reflect more detailed steps that may be delineated in Test Case steps.

**Comment by kengdoj** [comment]
@drewnielson , is this the same as Issue #208?

**Comment by drewnielson** [comment]
Ummm, maybe? Yes, can probably get rid of this one specifically for 6. Images and just cover it under #208 as the broader issue for other Baseline tests where the same step would be necessary.

**Comment by kengdoj** [comment]
Ok, this is a duplicate of #208 so closing.
