### ISSUE TITLE
Do we need a glossary page?

### ISSUE THREAD

**Issue by kengdoj** [Section508Coordinators/ICTTestingBaseline#214]
I think a page of terms and definitions would be helpful. We use terms defined already on other online sites, but would be good to have it in case those sources change.

**Comment by drewnielson** [comment]
Agreed - a glossary of terms would be helpful. Hopefully a shared resource
between the Baseline and the Baseline Alignment pages. Also would suggest
we stay as close as possible and/or reuse definitions already cited in the
508 reg and in WCAG.

**Comment by kengdoj** [comment]
MH, AN, KE: add as appendix

term (link to source definition) - paste definition

**Comment by kengdoj** [comment]
Some existing glossary resources:

[ACT glossary (in progress)](https://act-rules.github.io/glossary/)
[wcag glossary](https://www.w3.org/TR/WCAG21/#glossary)

**Comment by kengdoj** [comment]
@bletalien - please browse through the test cases to identify terms that a viewer may need definition or further explanation. Even if the term is defined within the test, please list that but include the test where you found it. Thanks!

**Comment by kengdoj** [comment]
USAB (temporary) link to definitions: https://beta.access-board.gov/ict/ch1e/#E103.4 or

https://www.access-board.gov/guidelines-and-standards/communications-and-it/about-the-ict-refresh/final-rule/text-of-the-standards-and-guidelines#E103-definitions

**Comment by kengdoj** [comment]
Links need unique names. I will fix.
