### ISSUE TITLE
Update 3. Focus Order for non-focusable revealed content

### ISSUE THREAD

**Issue by kengdoj** [Section508Coordinators/ICTTestingBaseline#225]
Add consideration for when revealed content does not have a focusable element in test instruction (bolded):

> Test Instructions
Use the keyboard to navigate through interface components.
Use the keyboard to activate trigger controls that reveal hidden content (menus, dialogs, expandable tree list, etc.).
**Check that focus is moved to the revealed content. (It is acceptable to TAB once or use an arrow key to move the focus forward into the revealed content.)
Advance the focus through the revealed content.**

https://section508coordinators.github.io/ICTTestingBaseline/03FocusOrder.html

**Comment by AnnMarieDavis** [comment]
I don't think the arrow key is clear that you can only use it one time. What about: 
(It is acceptable to press a TAB or arrow key once to move focus into the revealed content.)
