### ISSUE TITLE
Add identifiers & remove SC references from each test name 

### ISSUE THREAD

**Issue by kengdoj** [Section508Coordinators/ICTTestingBaseline#230]
Tests currently are referenced by full name only. 

1. Add (IDs) identifiers will make it easier to reference Baseline tests and map test cases to them.

2. Consider renaming the tests to be more descriptive and remove SCs. 

Ex:
> Test Procedures for SC 1.4.5 Images of Text

Incorporating both changes, this could be 6.D Test Procedures for Images of Text.

(Related to Issue #234 )

**Comment by kengdoj** [comment]
Group Discussion: 

- Baseline Requirement: _**10-Forms**_, (also considered: BL10 Forms)
  - Baseline Test: _**10.1-FormName**_, (also considered: BL10.1 Form Name, BL10.1-FormName) 
    - Baseline Test Instruction 1: _**10.1-FormName-1**_, (also considered BL10.1.1, BL10.1-FormName-nonempty, BL10.1-FormName-1)

**Comment by kengdoj** [comment]
This is a [sample of using suggested IDs](https://github.com/Section508Coordinators/ICTTestingBaseline/blob/kengdoj-removeSCTestResults/docs/04RepetitiveContent.md). 

I think using "10.#" for the Baseline Test looks very similar to the SCs and can be confusing.

**Comment by cliffbert** [comment]
It does look similar ...

**Comment by AnnMarieDavis** [comment]
I support using the format options 
     Baseline Requirement: 10-Forms
     Baseline Test: 10.1-FormName
     Baseline Test Instruction 1: 10.1-FormName-1

**Comment by kengdoj** [comment]
Here's a [sample with the #-TestName](https://github.com/Section508Coordinators/ICTTestingBaseline/blob/kengdoj-removeSCTestResults/docs/06Images.md) in the test results.

Adding the TestName seems to distinguish it from SCs better.
