### ISSUE TITLE
Add "non-empty" to test instructions for accname equivalent

### ISSUE THREAD

**Issue by kengdoj** [Section508Coordinators/ICTTestingBaseline#233]
This will aid in creating unique test cases for each instruction.

For [6. Images](https://section508coordinators.github.io/ICTTestingBaseline/06Images.html):

> 2. Check that the _**non-empty**_ combination of accessible name and accessible description provide an equivalent description. Numerous attributes contribute to the computation of the accessible name and accessible description. 

Other tests that have this instruction as well: [10 Forms](https://section508coordinators.github.io/ICTTestingBaseline/10Forms.html), [14. Links and Buttons](https://section508coordinators.github.io/ICTTestingBaseline/14Links.html), [19. iframes](https://section508coordinators.github.io/ICTTestingBaseline/19Frames.html). 

Consider how this change would affect the result for SC 1.1.1: When accname is empty, is it evaluated for SC 1.1.1? (This becomes a non-issue if we remove SCs from Baseline Test results as suggested in Issue #234.)

**Comment by akingkci** [comment]
See my comment added to Kathy's proposed text for #235

**Comment by kengdoj** [comment]
Closed by PR #235.

@akingkci's comment in new issue #237
