### ISSUE TITLE
Where is this spec for aria role conflict?

### ISSUE THREAD

**Issue by kengdoj** [Section508Coordinators/ICTTestingBaseline#245]
From 12DataTables.md: 

> NOTE: according to HTML5 specifications, the `<table>` element and associated elements and attributes may not be used in combination with ARIA role="table" and associated roles and attributes. If a table combines these techniques, it fails this test.

(Please cite the source so it can be linked.)

**Comment by drewnielson** [comment]
I'll make and propose changes in the file, but also keeping track here:

[HTML 5 Spec > 4.9.1 The table element > Allowed ARIA role attribute values](https://www.w3.org/TR/html52/tabular-data.html#ref-for-allowed-aria-role-attribute-values⑦④):
Allowed ARIA role attribute values:
> table role (default - ***do not set***), any other role value.

[HTML 5 Spec > 3. Semantics, structure, and APIs of HTML documents > 3.2.8.1 ARIA Authoring Requirements > 1st note](https://www.w3.org/TR/html52/dom.html#do-not-set)
> **NOTE:**
> In the majority of cases setting an ARIA role and/or aria-* attribute that matches the default implicit ARIA semantics is unnecessary and not recommended as these properties are already set by the browser.

[ARIA spec > table role](https://www.w3.org/TR/wai-aria-1.1/#table):
> Authors ***SHOULD*** prefer the use of the host language's semantics for table whenever possible, such as the HTML table element.
