### ISSUE TITLE
Decorative Images Test

### ISSUE THREAD

**Issue by kengdoj** [Section508Coordinators/ICTTestingBaseline#248]
Use the WCAG definition:

1.1.1 Non-text Content

All non-text content that is presented to the user has a text alternative that serves the equivalent purpose, except for the situations listed below. 

> Decoration, Formatting, Invisible: If non-text content is pure decoration, is used only for visual formatting, or is not presented to users, then it is implemented in a way that it can be ignored by assistive technology.

Suggestion to update Identify Content: Remove described in text and add terms from above definition

**Comment by drewnielson** [comment]
Agree with proposed change

**Comment by kengdoj** [comment]
WG agreed to -

Suggestion to update Identify Content: Remove described in text and add terms from above definition
