### ISSUE TITLE
Create custom Jekyll theme

### ISSUE THREAD

**Issue by drewnielson** [Section508Coordinators/ICTTestingBaseline#258]
Use site template and styles from the Alignment Framework repository (BaselineTestPages), to create common look and feel between the two published sites and resolve issues related to styles.

Modify style to fix issues #218 and #244

**Comment by kengdoj** [comment]
What do you think about using the [Docsy Jekyll theme](https://jekyll-themes.com/docsy-jekyll/)? This may be more work than we want to do now for this release but it seems to be a good fit for the Baseline doc.

**Comment by drewnielson** [comment]
It is pretty easy to switch themes. I'll give it a run-though in a separate
fork just to make sure we don't introduce any other accessibility issues
unknowingly.

**Comment by drewnielson** [comment]
@kengdoj, fixed the nested list numbering and link underlines with latest commit. I still like the idea of the Docsy Jekyll theme, but it will take some customization of nav bars (top nav and left side nave). Totally do-able, but I would suggest we save for the next minor update 3.0.x.

**Comment by kengdoj** [comment]
Awesome, thanks @drewnielson! 

Agree - I'll move this out of the 3.0 release project.

**Comment by kengdoj** [comment]
staging branch uses atbcb layouts.
