### ISSUE TITLE
Update Appendix B - Change Log

### ISSUE THREAD

**Issue by kengdoj** [Section508Coordinators/ICTTestingBaseline#265]
@drewnielson - is there an easy way to get these changes?

**Comment by drewnielson** [comment]
Yes, go to the commits link to see a list of all of the commits and commit messages. 
![image](https://user-images.githubusercontent.com/29068131/92962468-f55ec580-f43e-11ea-94db-b4e2d1cbe2cf.png)

If the commit messages are not very descriptive, then you can also click on each commit ID link to see a differential view of each line/file change for that particular commit.

**Comment by kengdoj** [comment]
Thanks for that info. 

I'm having second thoughts on listing changes from 2.x to 3.0 - 

Since 3.0 is a complete overhaul from version 2.x (which is fairly unknown), I suggest the change log in 3.0 be a blank slate and we keep track of changes after 3.0 is released. 

What do you think?

**Comment by bruce-usab** [comment]
FWIW, WAI Silver is now going by WCAG 3.0.  We saw the ITIC folks when they started calling an updated VPAT2 as VPAT 2.1 -- since people all assumed that meant it harmonized with WCAG 2.1.

If you can think of a different versioning scheme, that might help when this goes out for wider review.

**Comment by kengdoj** [comment]
WG discussion to note major/significant changes: 
- consolidated focus tests (2 & 3) into Baseline Test 2
- removed buttons from Links Baseline Test and included buttons in Forms
- changed Baseline Test number for Conforming Alt Version
- ID numbers added to each test
- Section 508/WCAG requirement mapped within test instructions
but there are greater differences that may not be worth detailing in 3.0 since 2.x was limited to TT development.

Decision:
Info for the Baseline 3.0 introduction:
- Revised 508
- new structure (pass vs. failure language)
- tool agnostic
- what to test, not how
