### ISSUE TITLE
Color contrast error on links on github ICTcoordinators site

### ISSUE THREAD

**Issue by cewalker1968** [Section508Coordinators/ICTTestingBaseline#274]
The links on the ICTBaseline pages have a color contrast of 4.02 to one.  The foreground color is #0f79d0. and the background color is #f2f2f2.   This is lower than the necessary 4.5 to one color contrast.   

The color is defined in the style.css sheet.  If this could be increased  so the contrast is above the minimum of 4.5, that would be appreciated. 

We, at the VA, link to this site with our contractors and testers and a few of them have 'complained'.

**Comment by drewnielson** [comment]
Thanks for the catch. Fixed.
