### ISSUE TITLE
Determine how to address Conformance Requriement 5

### ISSUE THREAD

**Issue by drewnielson** [Section508Coordinators/ICTTestingBaseline#28]
`5.` Non-Interference: If  technologies are used in a way that is not accessibility supported, or if they are used in a non-conforming way, then they do not block the ability of users to access the rest of the page. In addition, the Web page as a whole continues to meet the conformance requirements under each of the following conditions:
1. when any technology that is not relied upon is turned on in a user agent,
2. when any technology that is not relied upon is turned off in a user agent, and
3. when any technology that is not relied upon is not supported by a user agent
In addition, the following success criteria apply to all content on the page, including content that is not otherwise relied upon to meet conformance, because failure to meet them could interfere with any use of the page:
* 1.4.2 - Audio Control,
* 2.1.2 - No Keyboard Trap,
* 2.3.1 - Three Flashes or Below Threshold, and
* 2.2.2 - Pause, Stop, Hide.

**Comment by mraccess77** [comment]
I see 2 situations where the 4 SC above need to be tested:
1. When you have a non-conformant page that links to a conforming page -- test the above on the non-conforming page.
2. When a page uses technology that is not relied on for conformance but one of the 3 situations above is present test the 4 above SC. 
a. Examples would be JavaScript is not required for a page and the user has JavaScript turned off
b. Flash is not required for the page and Flash is not supported
c. Silverlight is not required for the page and Silverlight is turned on

**Comment by mraccess77** [comment]
Another situation where this occurs is when you have a non-conformant control on a page such as chart but you have a conformant alternative on the page.  This allows the page as a whole continues to conform per CR No. 2.    However, you can't have one of these 4 SC listed above occur in that non-conformant content.

**Comment by drewnielson** [comment]
Reference to Conformance Requirements incorporated in specific relevant SCs and in Alternate Versions baseline.
