### ISSUE TITLE
Introduction Page - Links are Redirected to Much Longer URLs than the Ones on the Page

### ISSUE THREAD

**Issue by jfc3-dol** [Section508Coordinators/ICTTestingBaseline#3]
On the Introduction page ( https://section508coordinators.github.io/ICTTestingBaseline/introduction.html ), the three links "415.1", "415.1.1", and "415.1.2" are redirected to much longer URLs than the ones on the page. Updating them to the current URL will help users find them if they change again.

**Comment by kengdoj** [comment]
Cloned issue to atbcb repo
