### ISSUE TITLE
Repetitive Content Page - Not Sure Why the Word AND is Capitalized

### ISSUE THREAD

**Issue by jfc3-dol** [Section508Coordinators/ICTTestingBaseline#6]
On the Repetitive Content page ( https://section508coordinators.github.io/ICTTestingBaseline/04RepetitiveContent.html ), I'm not sure why the word AND is capitalized between the H70 and G40 links?

Maybe make the text bold instead of capitalized, so people realize there are two links on the line, or maybe if possible, place the second link in a separate list item.

**Comment by kengdoj** [comment]
Cloned issue to atbcb repo
