### ISSUE TITLE
Forms Page - Markup Code is on the Page Instead of Link

### ISSUE THREAD

**Issue by jfc3-dol** [Section508Coordinators/ICTTestingBaseline#8]
On the Forms page ( https://section508coordinators.github.io/ICTTestingBaseline/10Forms.html ), there is markup code shown below and made bold on the page instead of the expected link.

Form components that change are tested in **`[Baseline 5. Changing Content](/ICTTestingBaseline/05Changing.html)`**.

**Comment by kengdoj** [comment]
Cloned issue to atbcb repo
